- name: Update cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Add backports repository
  ansible.builtin.apt_repository:
    repo: "deb http://deb.debian.org/debian bookworm-backports main"
    state: present
    update_cache: true

- name: Install obfs4_packages_utils_deb
  ansible.builtin.package:
    name: "{{ obfs4_packages_utils_deb }}"
    default_release: bookworm-backports
    state: present

- name: Ensure torproject gpg key is installed (A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89)
  ansible.builtin.apt_key:
    url: https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc
    id: A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89
    state: present

- name: Ensure torproject.org repository is present (APT)
  become: true
  apt_repository:
    repo: 'deb https://deb.torproject.org/torproject.org bookworm main'
    state: present
    update_cache: true

- name: Install Tor packages
  ansible.builtin.package:
    name: "{{ obfs4_packages_tor_deb }}"
    state: present

- name: Add torrc config
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/tor/{{ item }}"
    mode: 0644
  with_items:
    - torrc

- name: Start/restart service Tor
  ansible.builtin.service:
    name: tor
    enabled: true
    state: restarted

- name: Allow port 443
  community.general.ufw:
    rule: allow
    port: 443

- name: Allow port 3389
  community.general.ufw:
    rule: allow
    port: 3389
